---
title: "Sampled Dwellings"
date: "05/03/2020"
output: pdf_document
params:
  selected_cluster: NA
  sampled_dwellings: NA
classoption: portrait
header-includes:
   - \usepackage{float}
---

```{r, include=FALSE}

library(dplyr)
library(knitr)
library(kableExtra)

#####################################
# FOR TESTING ONLY
#####################################

  # source("R/load_data.R")
  # clusters <- load_clusters()
  # selected_cluster <- subset(clusters, id == "140582")
  # dwellings <- load_dwellings(selected_cluster$id)
  # sampled_dwellings <- subset(dwellings, sampled == 1)
  # 
  # sampled_dwellings$visit1 <- "[    ]"
  # sampled_dwellings$visit2 <- "[    ]"
  # sampled_dwellings$visit3 <- "[    ]"
  # 
  # sampled_dwellings$success<-"[   ]"
  # sampled_dwellings$salt_collected<-"[   ]"
  # sampled_dwellings$urine_1<-"[   ]"
  # sampled_dwellings$urine_2<-"[   ]"
  # sampled_dwellings$comments<-""
  # 
  # sampled_dwellings<-sampled_dwellings %>%
  #   select(visual_address, visit1, visit2, visit3, success, salt_collected, urine_1, urine_2, comments)

```


```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```


## Ukraine Iodine - Sampled Dwellings for Cluster: `r params$selected_cluster`

```{r echo=FALSE}
kable(
  params$sampled_dwellings, 
  format = "latex",
  row.names = FALSE,
  col.names = c("HH No.", "Address", "Visit 1", "Visit 2", "Visit 3", "Success", "Salt", "Urine 1", "Urine 2")
  ) %>%
  kable_styling(
      latex_options = c("scale_down")
  )

```




